name: "Github actions DB images"

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/githubactions-db.yml"
      - "githubactions-db/**"
  pull_request:
    paths:
      - ".github/workflows/githubactions-db.yml"
      - "githubactions-db/**"
  schedule:
    - cron:  '0 0 * * 1'
  # Enable manual run
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        include:
          - {image: "mariadb", version: "10.9", config-dir: "/etc/mysql/conf.d"}
          - {image: "mysql", version: "8.0", config-dir: "/etc/mysql/conf.d"}
    steps:
      - name: "Set variables"
        run: |
          OUTPUTS="type=image"
          if [[ "${{ github.ref }}" = 'refs/heads/master' && "${{ github.repository }}" = '${{ vars.USER_NAME }}/${{ vars.REPO_NAME }}' ]]; then
              OUTPUTS="$OUTPUTS,push=true"
          fi
          echo "OUTPUTS=$OUTPUTS" >> $GITHUB_ENV
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v2"
      - name: "Login to DockerHub"
        uses: "docker/login-action@v2"
        with:
          username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          password: "${{ secrets.DOCKER_HUB_TOKEN }}"
      - name: "Login to Github container registry"
        uses: "docker/login-action@v2"
        with:
          registry: "ghcr.io"
          username: "${{ secrets.GHCR_USERNAME }}"
          password: "${{ secrets.GHCR_ACCESS_TOKEN }}"
      - name: "Build and push"
        uses: "docker/build-push-action@v3"
        with:
          build-args: |
            BASE_IMAGE=${{ matrix.image }}:${{ matrix.version }}
            CONFIG_DIR=${{ matrix.config-dir }}
          cache-from: "type=gha"
          cache-to: "type=gha,mode=max"
          context: "githubactions-db"
          outputs: "${{ env.OUTPUTS }}"
          push: true
          tags: "ghcr.io/${{ vars.USER_NAME }}/githubactions-${{ matrix.image }}:${{ matrix.version }}"
